POST http://localhost:8080/events
content-type: application/json
authorization: xxx

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:43:00.000Z"
}

// rest-client extension